name: llm_error
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - ghostscript
  - pip
  - pip:
      - numpy
      - pypdf2
      - pymupdf
      - openai
      - anthropic
      - google-generativeai
      - arxiv
      - openreview-py